---
services:
  spark:
    image: tabulario/spark-iceberg
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ALLOW_HTTP: ${AWS_ALLOW_HTTP}
      AWS_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
    configs:
      - source: spark_defaults_conf
        target: /opt/spark/conf/spark-defaults.conf

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
  tansu:
    image: ${TANSU_IMAGE}
    pull_policy: always
    restart: unless-stopped
    environment:
      ADVERTISED_LISTENER_URL: ${ADVERTISED_LISTENER_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ALLOW_HTTP: ${AWS_ALLOW_HTTP}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DATA_LAKE: ${DATA_LAKE}
      ICEBERG_CATALOG: ${ICEBERG_CATALOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
      RUST_LOG: ${RUST_LOG}
      SCHEMA_REGISTRY: ${SCHEMA_REGISTRY}
      STORAGE_ENGINE: ${STORAGE_ENGINE}
    volumes:
      - ./schema/:/schema/
      - ./data/:/data/
    ports:
      - 9092:9092
      - 9100:9100
  iceberg-catalog:
    image: apache/iceberg-rest-fixture
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CATALOG_CATALOG__IMPL: org.apache.iceberg.jdbc.JdbcCatalog
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: ${AWS_ENDPOINT}
      CATALOG_S3_PATH__STYLE__ACCESS: true
      CATALOG_URI: jdbc:sqlite:file:/tmp/iceberg_rest_mode=memory
      CATALOG_WAREHOUSE: ${DATA_LAKE}
    ports:
      - 8181:8181
    links:
      - minio
configs:
  spark_defaults_conf:
    file: conf/spark-defaults.conf
volumes:
  minio:
    driver: local
  grafana:
    driver: local
